name: Snyk Container
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Build backend image
      run: |
        chmod +x ./env
        ./env ${{ secrets.POSTGRES_PASSWORD }}
        chmod +x ./gradlew
        ./gradlew build -x test
        docker build -t backend .
      working-directory: './backend'
      
    - name: Scan backend
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: backend
#        args: --severity-threshold=high

    - name: Build frontend image
      run: docker build -t frontend ./frontend/.

    - name: Scan frontend
      #      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: frontend
#        args: --severity-threshold=high
